# Generated by Django 5.0.4 on 2024-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('manufacturing_date', models.DateField()),
                ('prize', models.IntegerField(max_length=10)),
            ],
        ),
    ]
